# Generated by Django 2.2.20 on 2021-04-25 17:54

import dashboard.models.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.CharField(choices=[(dashboard.models.choices.PlanPriceChoices('$0'), '$0'), (dashboard.models.choices.PlanPriceChoices('$10'), '$10'), (dashboard.models.choices.PlanPriceChoices('$25'), '$25')], default=dashboard.models.choices.PlanPriceChoices('$0'), max_length=3),
        ),
    ]
