# Generated by Django 2.2.20 on 2021-04-26 04:33

import dashboard.models.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='screenshot',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[(dashboard.models.choices.PlanNameChoices('Free'), 'Free'), (dashboard.models.choices.PlanNameChoices('Standard'), 'Standard'), (dashboard.models.choices.PlanNameChoices('Pro'), 'Pro')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(choices=[(dashboard.models.choices.PlanPriceChoices('$0'), '$0'), (dashboard.models.choices.PlanPriceChoices('$10'), '$10'), (dashboard.models.choices.PlanPriceChoices('$25'), '$25')], default='$0', max_length=3),
        ),
    ]
