# Generated by Django 2.2.20 on 2021-04-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
